server:
  port: 8812
spring:
  application:
    name: cart-service
  redis:
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
leyou:
  jwt:
    pubKeyPath: F:\Work\Java-Work\Reserch_LeYouMarket\Leyou-authentication\Leyou-authentication-common\src\main\resources\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称